var game,barrierVehicles="barrier barrier2 barrier3 barrier4 barrier5 barrier6 barrier7".split(" "),trees=["trees2"],curse="HOPE YOU GOT\nINSURANCE;OUCH!;Doh!;Whoops,\nMY BAD!;AHHHH!;Not My fault...;Chee Hee!;MY RIMS!;Outta My Way,\nU Donkey!".split(";"),endCurse=["why u 2 bad"],bgColors=[16762461,8112292,5030873,9659533,8157290,5803123,9193030,2775940,7557180],titleColors=[15820613,16563730,16762461,8112292,5030873,9659533,8157290],tunnelWidth=256,shipHorizonalSpeed=100,shipMoveDelay=0,shipVerticalSpeed=
15E6,swipeDistance=10,barrierSpeed=980,barrierGap=192,shipHealth=1,barrierIncreaseSpeed=3.03,tunnelBGSpeed=1200;
Barrier=function(a,b,c){var d=[(a.width-tunnelWidth)/2+30,(a.width+tunnelWidth)/2-30];c=a.rnd.between(0,1);Phaser.Sprite.call(this,a,d[c],-190,barrierVehicles[a.rnd.between(0,barrierVehicles.length-1)]);d=new Phaser.Rectangle(0,0,tunnelWidth/2,170);this.crop(d);a.physics.enable(this,Phaser.Physics.ARCADE);this.anchor.set(c,.5);this.body.velocity.y=b;this.body.immovable=!1;this.placeBarrier=!0;this.collideCar=!1;Barrier.prototype.update=function(){this.placeBarrier&&this.y>barrierGap&&(this.placeBarrier=
!1,playGame.prototype.addBarrier(this.parent,this.tint));this.y>a.height&&this.destroy()}};Barrier.prototype=Object.create(Phaser.Sprite.prototype);Barrier.prototype.constructor=Barrier;window.onload=function(){game=new Phaser.Game(640,960,Phaser.AUTO,"");game.state.add("Boot",boot);game.state.add("Preload",preload);game.state.add("TitleScreen",titleScreen);game.state.add("PlayGame",playGame);game.state.add("GameOverScreen",gameOverScreen);game.state.add("Win",winStateScreen);game.state.start("Boot")};
var boot=function(a){};boot.prototype={preload:function(){this.game.load.image("loading","assets/sprites/loading.png")},create:function(){game.scale.pageAlignHorizontally=!0;game.scale.pageAlignVertically=!0;game.scale.scaleMode=Phaser.ScaleManager.SHOW_ALL;console.log("game started");game.state.start("Preload")}};var preload=function(a){};
preload.prototype={preload:function(){var a=this.add.sprite(game.width/2,game.height/2,"loading");a.anchor.setTo(.5);game.load.setPreloadSprite(a);game.load.image("title","assets/sprites/titleLate4Work.png");game.load.image("barrier6","assets/sprites/motorcycle.png");game.load.image("titleRage","assets/sprites/honoluluRage.png");game.load.image("ragetitle","assets/sprites/roadRageTitle.png");game.load.image("closedToday","assets/sprites/closedToday.png");game.load.image("grassB","assets/sprites/grassB.png");
game.load.image("railB","assets/sprites/railB.png");game.load.image("playbutton","assets/sprites/playbutton.png");game.load.image("backsplash","assets/sprites/backsplash.png");game.load.image("tunnelbg","assets/sprites/roadSpriteSide.png");game.load.image("wall","assets/sprites/grassTile.png");game.load.image("pileUp","assets/sprites/pileUp.png");game.load.image("ship","assets/sprites/mainCar.png");game.load.image("barrier7","assets/sprites/ShitVic.png");game.load.image("smoke","assets/sprites/smoke2.png");
game.load.image("Sand","assets/sprites/Sand.png");game.load.image("barrier","assets/sprites/greyCar.png");game.load.image("barrier2","assets/sprites/police.png");game.load.image("barrier3","assets/sprites/fancyCar.png");game.load.image("barrier4","assets/sprites/coolCar.png");game.load.image("barrier5","assets/sprites/orangeCar.png");game.load.audio("bgmusic",["assets/sounds/oldSchoolBG.mp3","assets/sounds/oldSchoolBG.ogg"]);game.load.audio("explosion",["assets/sounds/explosion.mp3","assets/sounds/explosion.ogg"]);
game.load.audio("carStart",["assets/sounds/carStart.mp3","assets/sounds/carStart.ogg"]);game.load.audio("carStart",["assets/sounds/carStart.mp3","assets/sounds/carStart.ogg"]);game.load.audio("carCrash",["assets/sounds/Crash.mp3","assets/sounds/Crash.ogg"]);game.load.audio("honk",["assets/sounds/honk.mp3","assets/sounds/honk.ogg"]);game.load.audio("screech",["assets/sounds/screech.mp3","assets/sounds/screech.ogg"]);game.load.audio("AstonButton",["assets/sounds/Aston.mp3","assets/sounds/Aston.ogg"])},
create:function(){game.state.start("TitleScreen")}};var titleScreen=function(a){};
titleScreen.prototype={create:function(){game.add.tileSprite(0,0,game.width,game.height,"tunnelbg");game.add.image(game.width.centerX,game.height-650,"titleRage");var a=game.add.image(game.width/2,200,"title");a.tint=titleColors[game.rnd.between(0,titleColors.length-1)];a.anchor.set(.5);var a=game.add.tween(a).to({width:420,height:420},1500,"Linear",!0,0,-1),b=game.add.text(game.width/2+200,game.height-150,"GRAPHICS &\n PROGRAMMING \nby:Travis.Jorel.H.",{font:"20px Helvetica",fill:"#ffffff",align:"center"});
b.anchor.set(.5);b.stroke="#000000";b.strokeThickness=0;a.yoyo(!0);this.startCar=game.add.audio("carStart");this.startCar.play();a=game.add.button(game.width/2,game.height-150,"playbutton",this.startGame,this);a.anchor.set(.5);a.tint=16563730;game.add.tween(a).to({width:220,height:220},1500,"Linear",!0,0,-1).yoyo(!0)},startGame:function(){game.add.audio("AstonButton").play();game.time.events.add(.4*Phaser.Timer.SECOND,function(){console.log("it werks");this.fade("PlayGame")},this)},fade:function(a){var b=
this.game.add.graphics(0,0);b.beginFill(this.fadeColor,1);b.drawRect(0,0,this.game.width,this.game.height);b.alpha=0;b.endFill();this.nextState=a;s=this.game.add.tween(b);s.to({alpha:1},500,null);s.onComplete.add(this.changeState,this);s.start()},changeState:function(){this.game.state.start(this.nextState);this.fadeOut()},fadeOut:function(){var a=this.game.add.graphics(0,0);a.beginFill(this.fadeColor,1);a.drawRect(0,0,this.game.width,this.game.height);a.alpha=1;a.endFill();s=this.game.add.tween(a);
s.to({alpha:0},600,null);s.start()}};var playGame=function(a){};
playGame.prototype={create:function(){this.bgMusic=game.add.audio("bgmusic");this.bgMusic.loopFull(1);tintColor=bgColors[game.rnd.between(0,bgColors.length-1)];game.add.tileSprite(0,0,game.width,game.height,"tunnelbg").autoScroll(0,tunnelBGSpeed+=200);var a=game.add.tileSprite(-tunnelWidth/2,0,game.width/2,game.height,"wall");a.tint=tintColor;a.autoScroll(0,800);a=game.add.tileSprite((game.width+tunnelWidth)/2,0,game.width/2,game.height,"wall");a.tint=tintColor;a.autoScroll(0,800);a.tileScale.x=-1;
a=game.add.tileSprite(-tunnelWidth/2,0,160,game.height,"grassB");a.tint=tintColor;a.autoScroll(0,500);var b=game.add.tileSprite(game.width-60,0,60,game.height,"grassB");b.tint=tintColor;b.autoScroll(0,500);b.tileScale.x=-1;b.alpha=1;a.alpha=1;game.add.tileSprite(tunnelWidth-80,0,15,game.height,"railB").autoScroll(0,500);a=game.add.tileSprite(game.width-200,0,15,game.height,"railB");a.autoScroll(0,500);a.tileScale.x=-1;this.shipPositions=[(game.width-tunnelWidth)/2+52,(game.width+tunnelWidth)/2-52];
this.ship=game.add.sprite(this.shipPositions[0],860,"ship");this.ship.side=0;this.ship.destroyed=!1;this.ship.canMove=!0;this.ship.canSwipe=!1;this.ship.anchor.set(.5);this.game.physics.enable(this.ship,Phaser.Physics.ARCADE);game.input.onDown.add(this.moveShip,this);game.input.onUp.add(function(){this.ship.canSwipe=!0},this);this.smokeEmitter=game.add.emitter(this.ship.x+20,this.ship.y+30,20);this.smokeEmitter.makeParticles("smoke");this.smokeEmitter.setXSpeed(-15,15);this.smokeEmitter.setYSpeed(50,
150);this.smokeEmitter.setAlpha(.5,1);this.smokeEmitter.start(!1,1E3,40);this.verticalTween=game.add.tween(this.ship).to({y:-200},shipVerticalSpeed,Phaser.Easing.Linear.None,!0);this.barrierGroup=game.add.group();a=new Barrier(game,barrierSpeed,tintColor,this.ship);game.add.existing(a);this.barrierGroup.add(a);this.counter=25;this.text=0;this.text=game.add.text(game.width/2,game.height-700,"READY GO!",{font:"34px helvetica",fill:"#FFDC00",align:"center"});this.text.anchor.setTo(.5);game.time.events.loop(Phaser.Timer.SECOND,
this.updateCounter,this);game.world.setBounds(-50,-50,game.world.width+100,game.world.height+100);game.world.camera.position.set(0);this.countDownTimer=game.time.events.loop(25*Phaser.Timer.SECOND,this.winCounter,this)},winCounter:function(){this.fade("Win");this.bgMusic.stop()},updateCounter:function(){this.counter--;this.text.setText("Get to Work in \n"+this.counter+" Seconds!")},moveShip:function(){this.ship.canSwipe=!0;this.ship.canMove&&3>=shipHealth&&(game.add.audio("screech").play(),this.ship.canMove=
!1,this.ship.side=1-this.ship.side,this.ship.angle=1==this.ship.side?30:-30,game.add.tween(this.ship).to({x:this.shipPositions[this.ship.side]},shipHorizonalSpeed,Phaser.Easing.Linear.None,!0).onComplete.add(function(){game.time.events.add(shipMoveDelay,function(){this.ship.canMove=!0;this.ship.angle=0},this)},this))},update:function(){this.smokeEmitter.x=this.ship.x+9;this.smokeEmitter.y=this.ship.y+60;this.ship.destroyed||game.physics.arcade.collide(this.ship,this.barrierGroup,null,function(a,b){game.time.events.remove(this.countDownTimer);
this.counter=25;game.add.tween(b).to({x:b.x+game.rnd.between(-100,100),y:b.y+game.rnd.between(-500,800),rotation:5},1E3,Phaser.Easing.Linear.None,!0).onComplete.add(function(){var a=game.add.emitter(b.x,b.y,200);a.makeParticles("smoke");a.setAlpha(.5,1);a.minParticleScale=.5;a.maxParticleScale=2;a.start(!0,2E3,null,200);game.add.audio("carCrash").play();b.destroy()},this);var c=game.add.audio("explosion");c.play();this.addQuake();var d=curse[game.rnd.between(0,curse.length-1)],d=game.add.text(game.width/
2,game.height/2,d,{font:"75px helvetica",fill:"#ffffff",align:"center"});d.anchor.set(.5);d.stroke="#000000";d.strokeThickness=8;game.add.audio("honk").play();this.ship.destroyed=!0;this.smokeEmitter.destroy();game.add.tween(this.ship).to({x:this.ship.x+game.rnd.between(-100,100),y:this.ship.y+game.rnd.between(-500,800),rotation:20},1E3,Phaser.Easing.Linear.None,!0).onComplete.add(function(){this.bgMusic.stop();c.play();var a=game.add.emitter(this.ship.x,this.ship.y,200);a.makeParticles("smoke");
a.setAlpha(.5,1);a.minParticleScale=.5;a.maxParticleScale=2;a.start(!0,2E3,null,200);game.add.audio("carCrash").play();this.ship.destroy();game.time.events.add(2*Phaser.Timer.SECOND,function(){this.ship.destroy();this.fade("GameOverScreen")},this)},this)},this)},fade:function(a){var b=this.game.add.graphics(0,0);b.beginFill(this.fadeColor,1);b.drawRect(0,0,this.game.width,this.game.height);b.alpha=0;b.endFill();this.nextState=a;s=this.game.add.tween(b);s.to({alpha:1},500,null);s.onComplete.add(this.changeState,
this);s.start()},changeState:function(){this.game.state.start(this.nextState);this.fadeOut()},fadeOut:function(){var a=this.game.add.graphics(0,0);a.beginFill(this.fadeColor,1);a.drawRect(0,0,this.game.width,this.game.height);a.alpha=1;a.endFill();s=this.game.add.tween(a);s.to({alpha:0},600,null);s.start()},restartShip:function(){if(!this.ship.destroyed&&1==this.ship.alpha){barrierSpeed*=barrierIncreaseSpeed;for(var a=0;a<this.barrierGroup.length;a++)this.barrierGroup.getChildAt(a).body.velocity.y=
barrierSpeed;3E3<=barrierSpeed&&(barrierSpeed=1090)}this.ship.canSwipe=!1;this.verticalTween.stop();this.verticalTween=game.add.tween(this.ship).to({y:860},100,Phaser.Easing.Linear.None,!0);this.verticalTween.onComplete.add(function(){this.verticalTween=game.add.tween(this.ship).to({y:0},shipVerticalSpeed,Phaser.Easing.Linear.None,!0)},this)},addBarrier:function(a,b){var c=new Barrier(game,barrierSpeed,b);game.add.existing(c);a.add(c)},addQuake:function(){var a={x:game.camera.x-10},b=Phaser.Easing.Bounce.InOut;
game.add.tween(game.camera).to(a,100,b,!1,0,4,!0).start()},addCarShake:function(){var a={x:ship.x-10},b=Phaser.Easing.Bounce.InOut;game.add.tween(ship.x).to(a,100,b,!1,0,4,!0).start()}};var winStateScreen=function(a){};
winStateScreen.prototype={create:function(){console.log("YOU WIN!");game.add.tileSprite(0,0,game.width,game.height,"backsplash").tint=bgColors[game.rnd.between(0,bgColors.length-1)];var a=game.add.image(game.width/2,game.height/2+25,"closedToday"),b=game.add.text(game.width/2,game.height/2-300,"CONGRATULATIONS!\n you got to work, on time \n but soon after you realize that \nnobody is there, it's a holiday\n today is your day off...",{font:"40px helvetica",fill:"#ffffff",align:"center",fontWeight:"bold"});
a.anchor.set(.5);b.anchor.set(.5);b.stroke="#000000";b.strokeThickness=6;a=game.add.button(game.width/2,game.height-150,"playbutton",this.startGame,this);a.anchor.set(.5);game.add.tween(a).to({width:220,height:220},1500,"Linear",!0,0,-1).yoyo(!0);game.world.camera.position.set(0)},startGame:function(){game.add.audio("AstonButton").play();this.fade("TitleScreen")},fade:function(a){var b=this.game.add.graphics(0,0);b.beginFill(this.fadeColor,1);b.drawRect(0,0,this.game.width,this.game.height);b.alpha=
0;b.endFill();this.nextState=a;s=this.game.add.tween(b);s.to({alpha:1},500,null);s.onComplete.add(this.changeState,this);s.start()},changeState:function(){this.game.state.start(this.nextState);this.fadeOut()},fadeOut:function(){var a=this.game.add.graphics(0,0);a.beginFill(this.fadeColor,1);a.drawRect(0,0,this.game.width,this.game.height);a.alpha=1;a.endFill();s=this.game.add.tween(a);s.to({alpha:0},600,null);s.start()}};var gameOverScreen=function(a){};
gameOverScreen.prototype={create:function(){barrierSpeed=880;shipHealth=1;game.add.tileSprite(0,0,game.width,game.height,"tunnelbg");game.add.image(game.width.centerX,400,"pileUp");var a=game.add.image(game.width/2,game.height-760,"ragetitle"),b=game.add.text(game.width/2,game.height-390,"WRECKED!",{font:"75px helvetica",fill:"#ffffff",align:"center"});b.stroke="#000000";b.strokeThickness=8;b.anchor.set(.5);a.tint=titleColors[game.rnd.between(0,titleColors.length-1)];a.anchor.set(.5);game.add.tween(a).to({width:420,
height:420},1500,"Linear",!0,0,-1).yoyo(!0);console.log("game over!");a=game.add.button(game.width/2,game.height-150,"playbutton",this.startGame,this);a.anchor.set(.5);a.tint=16563730;game.add.tween(a).to({width:220,height:220},1500,"Linear",!0,0,-1).yoyo(!0);game.world.camera.position.set(0)},startGame:function(){game.add.audio("honk").play();this.fade("PlayGame")},fade:function(a){var b=this.game.add.graphics(0,0);b.beginFill(this.fadeColor,1);b.drawRect(0,0,this.game.width,this.game.height);b.alpha=
0;b.endFill();this.nextState=a;s=this.game.add.tween(b);s.to({alpha:1},500,null);s.onComplete.add(this.changeState,this);s.start()},changeState:function(){this.game.state.start(this.nextState);this.fadeOut()},fadeOut:function(){var a=this.game.add.graphics(0,0);a.beginFill(this.fadeColor,1);a.drawRect(0,0,this.game.width,this.game.height);a.alpha=1;a.endFill();s=this.game.add.tween(a);s.to({alpha:0},600,null);s.start()}};